import { PageWrapper } from '@styles/globals';
import GlobalContext from '@utils/globalContext';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useContext, useEffect, useState } from 'react';
import { searchWars } from './api/swapi';
import Navbar from '@components/navbar';
import Details from '@components/details';

const ResultPage = () => {
    const router = useRouter();
    const slug = (router.query.slug as string[]) || [];
    const { currentResult, setCurrentResult } = useContext(GlobalContext);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        if (slug.length >= 1) {
            setLoading(false);
            searchWars([slug]).then((result) => {
                setCurrentResult(result[0]);
                setLoading(true);
            });
        }
    }, [slug]);

    return (
        <>
            <Head>
                <title>Star Wars search</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navbar />
                <PageWrapper align="left">
                    {!!loading && <Details data={currentResult} />}
                </PageWrapper>
            </main>
        </>
    );
};

export default ResultPage;
