import Searchbar from '@components/searchbar';
import Head from 'next/head';
import { PageWrapper } from '@styles/globals';
import Logo from '@components/logo';

const Home = () => {
    return (
        <>
            <Head>
                <title>Star Wars search</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <PageWrapper align="center">
                    <Logo />
                    <Searchbar />
                </PageWrapper>
            </main>

            <footer></footer>
        </>
    );
};

export default Home;
